Future fekiz added documenation links as comments
slack-samples/bolt-js-starter-template pull request #24
Opened 2022-06-22 21:42 UTC by neptunel

Added related documentation links for each listener in the starter template.

2022-06-22 21:44 UTC, srajiang commented on listeners/messages/sample-message.js
> +   -> send messages on Bolt: https://slack.dev/bolt-js/concepts#message-sending
```suggestion
   -> send messages with Bolt: https://slack.dev/bolt-js/concepts#message-sending
```

2022-06-22 22:03 UTC, stevengill requested changes
Looks great!

2022-06-22 22:03 UTC, stevengill commented on listeners/events/app-home-opened.js
> +   -> use events on Bolt:  https://slack.dev/bolt-js/concepts#event-listening
```suggestion
   -> use events with Bolt:  https://slack.dev/bolt-js/concepts#event-listening
```

2022-06-24 17:53 UTC, neptunel reviewed
Fixed the grammar tweaks! Can I merge now @stevengill ?

2022-06-24 19:05 UTC, stevengill approved these changes

2022-06-24 21:24 UTC, merged